CR_CHOICES = [
    ('all', 'All'),
    ('countryRU', 'Russian Federation'),
    ('countryUS', 'United States'),
    ('countryCN', 'China'),
    ('countryAF', 'Afghanistan'),
    ('countryAL', 'Albania'),
    ('countryDZ', 'Algeria'),
    ('countryAS', 'American Samoa'),
    ('countryAD', 'Andorra'),
    ('countryAO', 'Angola'),
    ('countryAI', 'Anguilla'),
    ('countryAQ', 'Antarctica'),
    ('countryAG', 'Antigua and Barbuda'),
    ]

GL_CHOICES = [
    ('all', 'All'),
    ('ru', 'Russian Federation'),
    ('us', 'United States'),
    ('cn', 'China'),
    ('af', 'Afghanistan'),
    ('al', 'Albania'),
    ('dz', 'Algeria'),
    ('as', 'American Samoa'),
    ('ad', 'Andorra'),
    ('ao', 'Angola'),
    ('ai', 'Anguilla'),
    ('aq', 'Antarctica'),
    ('ag', 'Antigua and Barbuda'),
]

LR_CHOICES = [
    ('all', 'All'),
    ('lang_ru', 'Russian'),
    ('lang_en', 'English'),
    ('lang_ar', 'Arabic'),
    ('lang_bg', 'Bulgarian'),
    ('lang_ca', 'Catalan'),
    ('lang_zh-CN', 'Chinese (Simplified)'),
    ('lang_zh-TW', 'Chinese (Traditional)'),
    ('lang_hr', 'Croatian'),
    ('lang_cs', 'Czech'),
    ('lang_da', 'Danish'),
    ('lang_nl', 'Dutch'),
    ('lang_et', 'Estonian'),
    ('lang_fi', 'Finnish'),
    ('lang_fr', 'French'),
    ('lang_de', 'German'),
    ('lang_el', 'Greek'),
    ('lang_iw', 'Hebrew'),
    ('lang_hu', 'Hungarian'),
    ('lang_is', 'Icelandic'),
    ('lang_id', 'Indonesian'),
    ('lang_it', 'Italian'),
    ('lang_ja', 'Japanese'),
    ('lang_ko', 'Korean'),
    ('lang_lv', 'Latvian'),
    ('lang_lt', 'Lithuanian'),
    ('lang_no', 'Norwegian'),
    ('lang_pl', 'Polish'),
    ('lang_pt', 'Portuguese'),
    ('lang_ro', 'Romanian'),
    ('lang_sr', 'Serbian'),
    ('lang_sk', 'Slovak'),
    ('lang_sl', 'Slovenian'),
    ('lang_es', 'Spanish'),
    ('lang_sv', 'Swedish'),
    ('lang_tr', 'Turkish'),
]